version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: ecommerce-db
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/ecommerce_db
      DB_USERNAME: postgres
      DB_PASSWORD: 1111
    depends_on:
      - db

volumes:
  postgres_data:
