version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ecommerce-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: /Users/ppc/Downloads/backend
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    env_file:
      - /Users/ppc/Downloads/backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
